In [1]:
import sqlite3
conn = sqlite3.connect('lab4.db')

c = conn.cursor()

In [2]:
# c.execute('''DROP TABLE gene;''')
# c.execute('''DROP TABLE enzyme;''')
# c.execute('''DROP TABLE en_pa;''')
# c.execute('''DROP TABLE pathway;''')

In [3]:
c.execute('''CREATE TABLE gene
             (id INT, ncbi_id TEXT, name_desc TEXT, organism TEXT, chr TEXT, start INT, end INT, eid INT, sequence TEXT )''')

c.execute('''CREATE TABLE enzyme
            (id INT, name TEXT, function TEXT, ecnum TEXT )''')

c.execute('''CREATE TABLE en_pa (eid INT, pid INT, priority INT )''')

c.execute('''CREATE TABLE pathway
             (id INT, name TEXT, description TEXT )''')

In [4]:
# Add pathway

pa_file = open("lab4_pathway_data")

name = ''
description = ''

iterator = 1

for i, line in enumerate(pa_file):

    line = line.replace('\n', '')
    
    if '#' in line:
        continue
        
    if i%3 is 0:
        name = line
    elif i%3 is 1:
        description = line
    elif i%3 is 2:
        c.execute("INSERT INTO pathway (id, name, description) VALUES ("+ str(iterator) + ", '" + name + "', '" + description + "' )" )        
        iterator+=1

conn.commit()

In [5]:
# Add enzyme

enz_file = open("lab4_enzyme_data")

name = ''
pathorder = []
function = ''
ECnum = ''

iterator = 1


for i, line in enumerate(enz_file):

    line = line.replace('\n', '')
    
    if '#' in line:
        continue
    if i%5 is 0:
        name = line
    elif i%5 is 1:
        pathorder = line.split(',')
        for i, item in enumerate(pathorder):
            pathorder[i] = pathorder[i].split('|')
            pathorder[i][1] = int(pathorder[i][1])
    elif i%5 is 2:
        function = line
    elif i%5 is 3:
        ECnum = line
    elif i%5 is 4:
        c.execute("INSERT INTO enzyme (id, name, function, ecnum) VALUES ("+ str(iterator) + ", '" + name + "', '" + function +"', '"+ ECnum + "' )" )
        
        ### TODO ###
        for rep in range(len(pathorder)):
            c.execute("INSERT INTO en_pa (eid, pid, priority) VALUES ("+ str(iterator) + "," + "(select id from pathway where name = "+"'"+pathorder[rep][0]+"')"+" ,"+str(pathorder[rep][1])+")")
            
        iterator+=1
        
conn.commit()

In [6]:
# #Search for Genes: Drosophila_melanogaster : Drosophila_melanogaster_sequen.fasta
# from Bio import Entrez
# from Bio import SeqIO
# from Bio.SeqRecord import SeqRecord

# #Enzyme List:
# #               Triosephosphate isomerase   
# #                 Phosphoglycerate kinase   
# #         Phosphoenolpyruvate carboxylase   
# #                         Pyruvate kinase   
# #       Glucose-6-phosphate dehydrogenase   
# #                        Gluconolactonase   
# #        6-phosphogluconate dehydrogenase   
# #                           Transaldolase   
# #                Succinate dehydrogenase   
# #                               Fumarase   
# #                  Malate dehydrogenase   
# #                      Citrate synthase

# # Possibble db




# Entrez.email = 'mike.ferna512@berkeley.edu'
# handle = Entrez.esearch(db='nucleotide',
#                        term='E coli Triosephosphate isomerase',
#                        sort='relevance',
#                        idtype='acc')

# for i in Entrez.read(handle)['IdList']:
#     handle = Entrez.efetch(db='nucleotide',id = i, rettype='fasta', retmode='text', retmax = 1)
#     ids = i;
#     break
# # make sure to view sequence before adding to database to be sure it is the correct sequence
# handle = Entrez.efetch(db="nucleotide", id= ids, rettype="fasta", retmode="text")
# record = handle.read()
# print(record)

In [7]:
# #----------------------#
# # Add sequence
    
# #record1 = open('Drosophila_melanogaster_sequen.fasta', 'a+')
# record1 = open('E_Coli_sequen.fasta', 'a+')
# #record1 = open('Homo_sapiens_sequen.fasta', 'a+')

# handle = Entrez.efetch(db="nucleotide", id= ids, rettype="fasta", retmode="text")
# record = handle.read()
# print(record)
# record1.write(record)

# Source of database data

We attempted to use the entrez package to load fasta data directly into fasta files for human, fruit fly and E coli. However when we attempted to search up certain sequences we had errors in the search results. Either to much data was being sent or the sequences themselves were not present. Although some of the sequences were loaded using the above method ultimatly most of the sequences were loaded by searching on https://www.ncbi.nlm.nih.gov/search for each sequence of each gene of each enzyme of each organism. 

# Missing Data 

For data that was  missing from the gene section, not found in https://www.ncbi.nlm.nih.gov/search for a specific organism, we added blank entries as place holders. For instance we could not find fumarase in Drosophila melanogaster so we added, XX_0 as a place holder for ncbi_id, N as a placeholder for the sequence. This formating was done for citrate synthase in Drosophila melanogaster, gluconolactonase and 6-phophogluconase dehydrogenase for Humans and for gluconolactonase in E coli.

In [8]:
# Add Gene

from Bio import SeqIO
import pandas as pd


gene_file = ['Drosophila_melanogaster_sequen.fasta', 'E_Coli_sequen.fasta', 'Homo_sapiens_sequen.fasta']
org_list = ['Drosophila melanogaster', 'Escherichia coli', 'Homo sapiens']
enz_list =    ['Triose phosphate isomerase' ,
                'Phosphoglycerate kinase'  ,
        'Phosphoenolpyruvate carboxylase'  ,
                        'Pyruvate kinase'  ,
      'Glucose-6-phosphate dehydrogenase'  ,
                       'Gluconolactonase'  ,
       '6-phosphogluconate dehydrogenase'  ,
                          'Transaldolase' ,
               'Succinate dehydrogenase' ,
                              'Fumarase', 
                 'Malate dehydrogenase',
                     'Citrate synthase' ]

chrRule = ['X', 'Y', 'R', 'L', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0']
# c.execute('''CREATE TABLE gene
#              (id INT, ncbi_id TEXT, name_desc TEXT, organism TEXT, chr TEXT, start INT, end INT, eid INT, sequence TEXT )''')

iterator = 1
for file in gene_file:
    for gene in SeqIO.parse(file, 'fasta'):
        
    # analysing information from FASTA
        
    # 1. id : iterating gene
        order_id = iterator
        
    # 2. ncbi_id : ncbi gene id
        ncbi_id = gene.id
        
    # 3. name_desc : name, description from fasta
        name_desc = gene.description[len(gene.id)+1: : ]
        
    # 4. organism
        organism = ''
        for org in org_list:
            if org in gene.description:
                organism = org
                break
                
    # 5. chromosome : (blank if not stated)
        chromosome = ''
        try:
            scan = str(gene.description)
            idx = scan.index('chromosome')
        
            while( scan[idx+11] in chrRule ):
                chromosome+=scan[idx+11]
                idx+=1
        except:
            pass
        
    # 6,7. st, en : starting / position in the gene
        st, en = '', ''
        
        try:
            scan = str(gene.name)
            idx = scan.index(':c')
            
            while( scan[idx+2] in chrRule ):
                st+=scan[idx+2]
                idx+=1
            idx+=1
            while( scan[idx+2] in chrRule ):
                en+=scan[idx+2]
                idx+=1
                if idx+2 is len(scan):
                    break
            st = int(st)
            en = int(en)
            
        except:
            st=0
            en=0
            pass


        
    # 8. eid : match enzyme id from the db
        eid = 0
        
        scan = str(gene.description)
        
        #print(scan)
        for enz in enz_list:
            if scan.lower().replace(' ', '').find(enz.lower().replace(' ','')) is not -1:
                input_str = enz[0].upper() + enz[1:].lower()
                output = str(pd.read_sql_query("SELECT id FROM enzyme WHERE name=="+"'"+str(input_str)+"'"+ ";", conn ))

                tmp = []
                idx = -1
                while( output[idx] is not ' '):
                    tmp.append(output[idx])
                    idx-=1

                tmp.reverse()
                eid = int("".join(tmp))
                break
                
    #9. seq : nt-sequence
        
        seq = str(gene.seq)
        
    # now, lets put to the db!
    
        c.execute("""INSERT INTO gene
             (id , ncbi_id , name_desc , organism , chr , start, end, eid, sequence )
             VALUES ("""
                 + str(order_id) + ', '
                 + "'" + ncbi_id + "', "
                 + "'" + name_desc + "', "
                 + "'" + organism + "', "
                 + "'" + chromosome + "', "
                 + str(st) + ', '
                 + str(en) + ', '
                 + str(eid)+ ', '
                 + "'" + seq + "'"
             
             +')'
        )
        

        iterator+=1
        
    conn.commit()

In [9]:
# print table

import pandas as pd

print (pd.read_sql_query("SELECT * FROM gene;",conn))
print (pd.read_sql_query("SELECT * FROM enzyme;", conn))
print (pd.read_sql_query("SELECT * FROM pathway;", conn))
print (pd.read_sql_query("SELECT * FROM en_pa;", conn))

    id                            ncbi_id  \
0    1     NT_033777.3:c30134599-30132981
1    2       NT_033779.5:c2753068-2746880
2    3         NZ_KB233235.1:c23004-20365
3    4                        NM_079724.3
4    5                         AH002543.2
5    6      NC_004354.4:12012377-12017375
6    7                           M80598.1
7    8                        NM_079111.3
8    9                        NM_057862.5
9   10                               XX_0
10  11                     NM_001298874.1
11  12                               XX_0
12  13       NC_000913.3:c4111507-4110740
13  14       NC_000913.3:c3072622-3071459
14  15       NC_000913.3:c4153098-4150447
15  16        NC_000913.3:1755698-1757110
16  17       NC_011751.1:c2171506-2170031
17  18                               XX_0
18  19       NC_000913.3:c2101268-2099862
19  20        NC_000913.3:2578666-2579616
20  21          NC_000913.3:755907-757673
21  22       NC_000913.3:c1686588-1685185
22  23       NC_000913.3:c3384268-3383330
23  24         NC_000913.3:c754468-753185
24  25                     NM_001258026.1
25  26     NC_000023.11:78104169-78126827
26  27                               XX_0
27  28    NC_000015.10:c72231624-72199029
28  29  NC_000023.11:c154547586-154531390
29  30                               XX_0
30  31                               XX_0
31  32                        NM_006755.1
32  33             NG_012340.1:5001-40449
33  34                           M15502.1
34  35     NC_000007.14:76048019-76067508
35  36    NC_000012.12:c56300391-56271699

                                            name_desc  \
0   Drosophila melanogaster chromosome 3R Triose p...
1   Drosophila melanogaster chromosome 2L Phosphog...
2   Phosphoenolpyruvate carboxylase Drosophila mel...
3   Drosophila melanogaster pyruvate kinase, trans...
4   Drosophila melanogaster glucose-6-phosphate de...
5   Drosophila melanogaster chromosome X: Gluconol...
6   Drosophila melanogaster 6-phosphogluconate deh...
7   Drosophila melanogaster transaldolase (Taldo),...
8   Drosophila melanogaster succinate dehydrogenas...
9                    Drosophila melanogaster fumarase
10  Drosophila melanogaster malate dehydrogenase 1...
11           Drosophila melanogaster citrate synthase
12  Escherichia coli str. K-12 substr. E coli Trio...
13  pgk phosphoglycerate kinase [ Escherichia coli...
14  ppc phosphoenolpyruvate carboxylase [ Escheric...
15  pykF pyruvate kinase I [ Escherichia coli str....
16  zwf glucose-6-phosphate dehydrogenase [ Escher...
17                  Escherichia coli gluconolactonase
18  gnd 6-phosphogluconate dehydrogenase, decarbox...
19  talA transaldolase A [ Escherichia coli str. K...
20  sdhA succinate dehydrogenase, flavoprotein sub...
21  umC fumarate hydratase (fumarase C),aerobic Cl...
22  malate dehydrogenase, NAD(P)-binding [ Escheri...
23  Citrate synthase [ Escherichia coli str. K-12 ...
24  Homo sapiens triose phosphate isomerase 1 (TPI...
25  Homo sapiens chromosome X, GRCh38.p12 Primary ...
26       Homo sapiens phosphoenolpyruvate carboxylase
27  Homo sapiens chromosome 15, pyruvate kinase M1...
28  Homo sapiens chromosome X,Glucose-6-phosphate ...
29                      Homo sapiens gluconolactonase
30      Homo sapiens 6-phosphogluconate dehydrogenase
31        Homo sapiens transaldolase 1 (TALDO1), mRNA
32  Homo sapiens succinate dehydrogenase complex i...
33  Homo sapiens mitochondrial fumarase mRNA, comp...
34  Homo sapiens chromosome 7,Malate dehydrogenase...
35  Homo sapiens chromosome 12, Citrate synthase, ...

                   organism chr      start        end  eid  \
0   Drosophila melanogaster  3R   30134599   30132981    1
1   Drosophila melanogaster  2L    2753068    2746880    2
2   Drosophila melanogaster          23004      20365    3
3   Drosophila melanogaster              0          0    4
4   Drosophila melanogaster              0          0    5
5   Drosophila melanogaster   X          0          0    6
6   Drosophila melanogaster              0          0    7
7   Drosophila melanogaster              0          0    8
8   Drosophila melanogaster              0          0    9
9   Drosophila melanogaster              0          0   10
10  Drosophila melanogaster              0          0   11
11  Drosophila melanogaster              0          0   12
12         Escherichia coli        4111507    4110740    1
13         Escherichia coli        3072622    3071459    2
14         Escherichia coli        4153098    4150447    3
15         Escherichia coli              0          0    4
16         Escherichia coli        2171506    2170031    5
17         Escherichia coli              0          0    6
18         Escherichia coli        2101268    2099862    7
19         Escherichia coli              0          0    8
20         Escherichia coli              0          0    9
21         Escherichia coli        1686588    1685185   10
22         Escherichia coli        3384268    3383330   11
23         Escherichia coli         754468     753185   12
24             Homo sapiens              0          0    1
25             Homo sapiens   X          0          0    2
26             Homo sapiens              0          0    3
27             Homo sapiens  15   72231624   72199029    4
28             Homo sapiens   X  154547586  154531390    5
29             Homo sapiens              0          0    6
30             Homo sapiens              0          0    7
31             Homo sapiens              0          0    8
32             Homo sapiens   1          0          0    9
33             Homo sapiens              0          0   10
34             Homo sapiens   7          0          0   11
35             Homo sapiens  12   56300391   56271699   12

                                             sequence
0   AAGCCGTTTATATAATTTCAGAATAACTTTTACTACTCCTTACTTA...
1   GCCGCGGCATTTGTACAGCCGCAGTCGATAAGACAACAACAACAGC...
2   ATGAATCAGCAATATTCCGCAATGCGCAGTAATGTCAGTATGTTGG...
3   AGTCGAACTTTTTGTCTCGTCCTCGCCGCGTCCGATTTTCCATATA...
4   CAGCTGCGCAGTCGGGGTTACAAAGCGTCTGCTGCTTTAGCTGTTG...
5   GTGTAGAAGGTGGCAGCCCTTTAAGGCACCAGCTGACCCCATAGAG...
6   CTCGAGCAGTTCAAGTTCCTGAAGTGAGTTGCGCCACCTTTGTCTT...
7   TATTGCATTGAAGTTGGGCAATGGGAAGTGATCGCACGTTAAAAAA...
8   AGCGAGTCAGTGAACCGAACTGCAGTGCCGACGAGCGGCAGTTCAC...
9                                                   N
10  AAAAAGTAGTGACTGGAAAATAATTGTGAAAAGTAACAGGTTCCCA...
11                                                  N
12  ATGCGACATCCTTTAGTGATGGGTAACTGGAAACTGAACGGCAGCC...
13  ATGTCTGTAATTAAGATGACCGATCTGGATCTTGCTGGGAAACGTG...
14  ATGAACGAACAATATTCCGCATTGCGTAGTAATGTCAGTATGCTCG...
15  ATGAAAAAGACCAAAATTGTTTGCACCATCGGACCGAAAACCGAAT...
16  ATGGCGGTAACGCAAACAGCCCAGGCCTGTGACCTGGTCATTTTCG...
17                                                  N
18  ATGTCCAAGCAACAGATCGGCGTAGTCGGTATGGCAGTGATGGGAC...
19  ATGAACGAGTTAGACGGCATCAAACAGTTCACCACTGTCGTGGCAG...
20  ATGAAATTGCCAGTCAGAGAATTTGATGCAGTTGTGATTGGTGCCG...
21  ATGAATACAGTACGCAGCGAAAAAGATTCGATGGGGGCGATTGATG...
22  ATGAAAGTCGCAGTCCTCGGCGCTGCTGGCGGTATTGGCCAGGCGC...
23  ATGGCTGATACAAAAGCAAAACTCACCCTCAACGGGGATACAGCTG...
24  CTCGCCGGCGTCCGCGTCCCCGCGCCGAGCTGCTCGGGCTCCCTGA...
25  GAGAGCAGCGGCCGGGAAGGGGCGGTGCGGGAGGCGGGGTGTGGGG...
26                                                  N
27  AACCCATAAATCTGGGCCCTGCCCAGGTAGGCCGGGACAGCTGGGG...
28  ACAAGCCCCGCCCCCGAGAACTCGGGAAGCCGGCGAGAAGTGTGAG...
29                                                  N
30                                                  N
31  CGCGCCCGTCCCGTCGCCGCCGCCGCCGCCGCAGACCCCTCGGTCT...
32  ACCCGGGAAACCGGAAGCCGCCTCCCACTTGGTTGCTCGTACGCGG...
33  ATGGCAAGCCAAAATTCCTTCCGGATAGAATATGATACCTTTGGTG...
34  TCCCGGAGGCGAGCGCGACCGGAAGTCCGGTCACTCTCGCGAGGCC...
35  AGTGGGCGGGGCCTCCTTGAGGACCCCGGGCTGGGCGCCGCCGCCG...
    id                               name  \
0    1         Triose phosphate isomerase
1    2            Phosphoglycerate kinase
2    3    Phosphoenolpyruvate carboxylase
3    4                    Pyruvate kinase
4    5  Glucose-6-phosphate dehydrogenase
5    6                   Gluconolactonase
6    7   6-phosphogluconate dehydrogenase
7    8                      Transaldolase
8    9            Succinate dehydrogenase
9   10                           Fumarase
10  11               Malate dehydrogenase
11  12                   Citrate synthase

                                             function        ecnum
0   catalyzes the reversible interconversion of th...   EC 5.3.1.1
1   catalyzes the reversible transfer of a phospha...   EC 2.7.2.3
2   an enzyme in the family of carboxy-lyases foun...  EC 4.1.1.31
3   It catalyzes the transfer of a phosphate group...  EC 2.7.1.40
4   D-glucose 6-phosphate + NADP⁺ ⇌ 6-phospho-D-gl...  EC 1.1.1.49
5   This enzyme belongs to the family of hydrolase...  EC 3.1.1.17
6   It forms ribulose 5-phosphate from 6-phosphogl...  EC 1.1.1.44
7   transaldolase:catalyzes the following reaction...   EC 2.2.1.2
8   This enzyme catalyzes the oxidation of succina...   EC 1.3.5.1
9   It catalyzes the reversible hydration/dehydrat...   EC 4.2.1.2
10  It reversibly catalyzes the oxidation of malat...  EC 1.1.1.37
11  It catalyzes the condensation reaction of the ...   EC 2.3.3.1
   id               name                                        description
0   1         glycolysis  metabolic pathway that converts glucose C6H12O...
1   2  pentose phosphate  metabolic pathway parallel to glycolysis, gene...
2   3          TCA cycle  a series of chemical reactions used by all aer...
    eid  pid  priority
0     1    1         1
1     2    1         3
2     3    1         4
3     4    1         5
4     4    2         5
5     5    2         1
6     5    1         2
7     6    2         2
8     7    2         3
9     8    2         4
10    9    3         1
11   10    3         2
12   11    3         3
13   12    3         4

Our goal for the database was to make it easy to align the genes from 3 three organisms with enzymes and have these enzymes map to their priority in the pathway.

In order to do this we created a gene, enzyme, enzyme pathway priority table and a pathway table. 

In the gene table there are 4 enzymes per the 3 pathways over 3 organsims making a total of 36 genes in the gene table. These genes each have an enzyme id, 'eid', that matchs that gene to an enzyme in the enzyme table via the 'id' colum in the enzyme table. This way we can call genes and have them align to enzymes. 

These enzymes then have a certain priority in a pathway, and some enzymes exsist in multiple pathways, the pathways we looked at were TCA cycle, glycolysis, and pentose phosphate. The 12 enzymes over 3 pathways each have a priority in the pathway(s) that they exsist in. So in order to match the enzymes with pathways, we created an associative table that matches enzyme id, 'eid', with a path id, 'pid'. This 'pid' is either 1 2 or 3 for the three pathways. This allows us to join any enzyme to the appropriate pathway. With all these aligned tables we are able to join all the table together to call any member of any table.

In [10]:
# view by enzyme priority in each pathway SORTED BY ORDER!! (sort enzymes by iwhere pid=1 and have priority information(priority>0))
print(pd.read_sql_query("SELECT enzyme.id, enzyme.name FROM enzyme INNER JOIN en_pa on enzyme.id = en_pa.eid WHERE en_pa.pid = 1 and en_pa.priority>=0 ORDER BY en_pa.priority ASC ;", conn))

#

   id                               name
0   1         Triose phosphate isomerase
1   5  Glucose-6-phosphate dehydrogenase
2   2            Phosphoglycerate kinase
3   3    Phosphoenolpyruvate carboxylase
4   4                    Pyruvate kinase